apiVersion: v1
kind: Service
metadata:
  namespace: lsc
  name: nginx-nfs-service
spec:
  selector:
    app: nginx-nfs
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
