apiVersion: batch/v1
kind: Job
metadata:
  namespace: lsc
  name: nfs-content-init
spec:
  template:
    spec:
      containers:
        - name: writer
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - echo "<h1>Hello from NFS!</h1>" > /data/index.html;
          volumeMounts:
            - name: web-content
              mountPath: /data
      restartPolicy: Never
      volumes:
        - name: web-content
          persistentVolumeClaim:
            claimName: http-claim
